const Router = require('express')
const router = new Router()
const carriagePriceRouter = require('./carriagePriceRouter')
const equipmentRouter = require('./equipmentRouter')
const orderRouter = require('./orderRouter')
const subscriptionPriceRouter = require('./subscriptionPriceRouter')
const transportRouter = require('./transportRouter')
const userInfoRouter = require('./userInfoRouter')
const userRatingRouter = require('./userRatingRouter')
const offerRouter = require('./offerRouter')
const userRouter = require('./userRouter')
const pointRouter = require('./pointRouter')
const partnerRouter = require('./partnerRouter')
const ratingRouter = require('./ratingRouter')
const fileRouter = require('./fileRouter')
const mailRouter = require('./mailRouter')
const notificationRouter = require('./notificationRouter')
const subscriptionRouter = require('./subscriptionRouter')
const settingRouter = require('./settingRouter')
const limitRouter = require('./limitRouter')
const stateRouter = require('./stateRouter')
const defaultDataRouter = require('./defaultDataRouter')
const managementRouter = require('./managementRouter')

router.use('/user', userRouter)
router.use('/user_rating', userRatingRouter)
router.use('/user_info', userInfoRouter)
router.use('/rating', ratingRouter)
router.use('/order', orderRouter)
router.use('/offer', offerRouter)
router.use('/point', pointRouter)
router.use('/transport', transportRouter)
router.use('/equipment', equipmentRouter)
router.use('/file', fileRouter)
router.use('/carriage_price', carriagePriceRouter)
router.use('/subscription_price', subscriptionPriceRouter)
router.use('/partner', partnerRouter)
router.use('/mail', mailRouter)
router.use('/notification', notificationRouter)
router.use('/subscription', subscriptionRouter)
router.use('/setting', settingRouter)
router.use('/limit', limitRouter)
router.use('/state', stateRouter)
router.use('/default_data', defaultDataRouter)

router.use('/management', managementRouter)

module.exports = router
